Deployment:
  Imagename: kubeshlomi/petclinic_proj
  label: petclinic
  labelselector: petclinic
Service:
  type: ClusterIP
  label: petclinic
  labelselector: petclinic
  port: 80
  targetport: 8080
Mysqldep:
  Imagename: mysql:5.7 
  label: petclinic
  labelselector: petclinic
  MYSQL_ROOT_PASSWORD:
  MYSQL_ALLOW_EMPTY_PASSWORD: true
  MYSQL_USER: petclinic
  MYSQL_PASSWORD: petclinic
  MYSQL_DATABASE: petclinic





