Deployment:
  Imagename: kubeshlomi/petclinic_proj
  label: petclinic
  labelselector: petclinic
Service:
  type: ClusterIP
  label: petclinic
  labelselector: petclinic
  port: 80
  targetport: 8080
Mysqldep:
  Imagename: mysql:5.7 
  label:
  labelselector:
  DepN:
configenv:
  MYSQL_ROOT_PASSWORD:
  MYSQL_ALLOW_EMPTY_PASSWORD:
  MYSQL_USER:
  MYSQL_PASSWORD:
  MYSQL_DATABASE:





