version: '3.1'
services:
  sonarqube:
      image: sonarqube
      restart: unless-stopped
      ports:
        - 0.0.0.0:9000:9000
        - 0.0.0.0:9092:9092
      networks:
       - welcome_jb 
  jenkins:
        build: ./jenkins/master
        image: jenkins/jenkins:jdk17
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        networks: 
            - welcome_jb
  jenkins-slave:
        build: ./jenkins/slave
        image: jenkins/slave:alpine
        # Removed container name to support scale out option 
        #container_name: jenkins-slave 
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
            - ./volume:/home/jenkins # Avoid mysql volume mount issue
        networks: 
        - welcome_jb
        depends_on:
            - jenkins 
networks:
  welcome_jb: