apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.Deployment.labelselector }}
  template:
    metadata:
      labels:
        app:  {{ .Values.Deployment.label }}
    spec:
      containers:
      - name: petclinic-container
        image: {{ .Values.Deployment.Imagename }}:latest
        resources:
          limits:
            memory: "556Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.Service.targetport }}
