apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.Mysqldep.label }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.Mysqldep.labelselector }}
  template:
    metadata:
      labels:
        app: {{ .Values.Mysqldep.label }}
    spec:
      containers:
      - name: mysql
        image: {{ .Values.Mysqldep.Imagename }}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.Mysqldep.MYSQL_ROOT_PASSWORD }}
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: {{ .Values.Mysqldep.MYSQL_ALLOW_EMPTY_PASSWORD }}
        - name: MYSQL_USER
          value: {{ .Values.Mysqldep.MYSQL_USER }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.Mysqldep.MYSQL_PASSWORD }}
        - name: MYSQL_DATABASE
          value: {{ .Values.Mysqldep.MYSQL_DATABASE }}